export const cards = [
  {
    title: 'Водолазка(normal)',
    price: '13,5',
    href: '/shop?id=0',
    src: 'public/images/1_Водолазка_normal__src.jpg',
    hoverSrc: 'public/images/1_Водолазка_normal__hover.jpg',
    season: 'Осень',
    category: 'Водолазка',
    images: [
      'public/images/shop/1_Водолазка_normal/01.jpg',
      'public/images/shop/1_Водолазка_normal/02.jpg',
      'public/images/shop/1_Водолазка_normal/03.jpg',
      'public/images/shop/1_Водолазка_normal/04.jpg',
      'public/images/shop/1_Водолазка_normal/05.jpg',
      'public/images/shop/1_Водолазка_normal/06.jpg',
      'public/images/shop/1_Водолазка_normal/07.jpg',
      'public/images/shop/1_Водолазка_normal/08.jpg',
      'public/images/shop/1_Водолазка_normal/09.jpg',
      'public/images/shop/1_Водолазка_normal/10.jpg',
      'public/images/shop/1_Водолазка_normal/11.jpg',
      'public/images/shop/1_Водолазка_normal/12.jpg',
      'public/images/shop/1_Водолазка_normal/13.jpg',
      'public/images/shop/1_Водолазка_normal/14.jpg',
      'public/images/shop/1_Водолазка_normal/15.jpg',
      'public/images/shop/1_Водолазка_normal/16.jpg',
    ],
  },
  {
    title: 'Куртка (normal)',
    price: '49,00',
    href: '/shop?id=1',
    src: 'public/images/2_Куртка__normal__src.jpeg',
    hoverSrc: 'public/images/2_Куртка__normal__hover.jpeg',
    season: 'Зима',
    category: 'Курки',
    images: [
      'public/images/shop/2_Куртка__normal/01.jpeg',
      'public/images/shop/2_Куртка__normal/02.jpeg',
      'public/images/shop/2_Куртка__normal/03.jpeg',
      'public/images/shop/2_Куртка__normal/04.jpg',
      'public/images/shop/2_Куртка__normal/05.jpg',
      'public/images/shop/2_Куртка__normal/06.jpg',
      'public/images/shop/2_Куртка__normal/07.jpg',
      'public/images/shop/2_Куртка__normal/08.jpg',
      'public/images/shop/2_Куртка__normal/09.jpg',
      'public/images/shop/2_Куртка__normal/10.jpg',
      'public/images/shop/2_Куртка__normal/11.jpg',
      'public/images/shop/2_Куртка__normal/12.jpg',
      'public/images/shop/2_Куртка__normal/13.jpg',
    ],
  },
  {
    title: 'Куртка (normal)',
    price: '49,50',
    href: '/shop?id=2',
    src: 'public/images/3_Куртка__normal__src.jpg',
    hoverSrc: 'public/images/3_Куртка__normal__hover.jpg',
    season: 'Зима',
    category: 'Курки',
    images: [
      'public/images/shop/3_Куртка__normal/01.jpg',
      'public/images/shop/3_Куртка__normal/02.jpg',
      'public/images/shop/3_Куртка__normal/03.jpg',
      'public/images/shop/3_Куртка__normal/04.jpg',
      'public/images/shop/3_Куртка__normal/05.jpg',
      'public/images/shop/3_Куртка__normal/06.jpg',
      'public/images/shop/3_Куртка__normal/07.jpg',
      'public/images/shop/3_Куртка__normal/08.jpg',
      'public/images/shop/3_Куртка__normal/09.jpg',
    ],
  },
  {
    title: 'Куртка (oversize)',
    price: '32,00',
    href: '/shop?id=3',
    src: 'public/images/4_Куртка__oversize__src.jpg',
    hoverSrc: 'public/images/4_Куртка__oversize__hover.jpg',
    season: 'Зима',
    category: 'Курки',
    images: [
      'public/images/shop/4_Куртка__oversize/01.jpg',
      'public/images/shop/4_Куртка__oversize/02.jpg',
      'public/images/shop/4_Куртка__oversize/03.jpg',
      'public/images/shop/4_Куртка__oversize/04.jpg',
      'public/images/shop/4_Куртка__oversize/05.jpg',
      'public/images/shop/4_Куртка__oversize/06.jpg',
      'public/images/shop/4_Куртка__oversize/07.jpg',
      'public/images/shop/4_Куртка__oversize/08.jpg',
      'public/images/shop/4_Куртка__oversize/09.jpg',
      'public/images/shop/4_Куртка__oversize/10.jpg',
      'public/images/shop/4_Куртка__oversize/11.jpg',
      'public/images/shop/4_Куртка__oversize/12.jpg',
      'public/images/shop/4_Куртка__oversize/13.jpg',
      'public/images/shop/4_Куртка__oversize/14.jpg',
    ],
  },
  {
    title: 'Мужская двойка(normal)',
    price: '29,00',
    href: '/shop?id=4',
    src: 'public/images/5_Мужская_двойка_normal__hover.jpg',
    hoverSrc: 'public/images/5_Мужская_двойка_normal__hover.jpg',
    season: 'Зима',
    category: 'Курки',
    images: [
      'public/images/shop/2_Куртка__normal/01.jpeg',
      'public/images/shop/2_Куртка__normal/02.jpeg',
      'public/images/shop/2_Куртка__normal/03.jpeg',
      'public/images/shop/2_Куртка__normal/04.jpg',
      'public/images/shop/2_Куртка__normal/05.jpg',
      'public/images/shop/2_Куртка__normal/06.jpg',
      'public/images/shop/2_Куртка__normal/07.jpg',
      'public/images/shop/2_Куртка__normal/08.jpg',
      'public/images/shop/2_Куртка__normal/09.jpg',
      'public/images/shop/2_Куртка__normal/10.jpg',
      'public/images/shop/2_Куртка__normal/11.jpg',
      'public/images/shop/2_Куртка__normal/12.jpg',
      'public/images/shop/2_Куртка__normal/13.jpg',
    ],
  },
  {
    title: 'Мужская кофта(normal)',
    price: '10,50',
    href: '/shop?id=5',
    src: 'public/images/6_Мужская_кофта_normal__src.jpg',
    hoverSrc: 'public/images/6_Мужская_кофта_normal__hover.jpg',
    season: 'Зима',
    category: 'Курки',
    images: [
      'public/images/shop/2_Куртка__normal/01.jpeg',
      'public/images/shop/2_Куртка__normal/02.jpeg',
      'public/images/shop/2_Куртка__normal/03.jpeg',
      'public/images/shop/2_Куртка__normal/04.jpg',
      'public/images/shop/2_Куртка__normal/05.jpg',
      'public/images/shop/2_Куртка__normal/06.jpg',
      'public/images/shop/2_Куртка__normal/07.jpg',
      'public/images/shop/2_Куртка__normal/08.jpg',
      'public/images/shop/2_Куртка__normal/09.jpg',
      'public/images/shop/2_Куртка__normal/10.jpg',
      'public/images/shop/2_Куртка__normal/11.jpg',
      'public/images/shop/2_Куртка__normal/12.jpg',
      'public/images/shop/2_Куртка__normal/13.jpg',
    ],
  },
  {
    title: 'Мужская кофта(normal)',
    price: '12,00',
    href: '/shop?id=6',
    src: 'public/images/7_Мужская_кофта_normal__src.jpg',
    hoverSrc: 'public/images/7_Мужская_кофта_normal__hover.jpg',
    season: 'Зима',
    category: 'Курки',
    images: [
      'public/images/shop/2_Куртка__normal/01.jpeg',
      'public/images/shop/2_Куртка__normal/02.jpeg',
      'public/images/shop/2_Куртка__normal/03.jpeg',
      'public/images/shop/2_Куртка__normal/04.jpg',
      'public/images/shop/2_Куртка__normal/05.jpg',
      'public/images/shop/2_Куртка__normal/06.jpg',
      'public/images/shop/2_Куртка__normal/07.jpg',
      'public/images/shop/2_Куртка__normal/08.jpg',
      'public/images/shop/2_Куртка__normal/09.jpg',
      'public/images/shop/2_Куртка__normal/10.jpg',
      'public/images/shop/2_Куртка__normal/11.jpg',
      'public/images/shop/2_Куртка__normal/12.jpg',
      'public/images/shop/2_Куртка__normal/13.jpg',
    ],
  },
  {
    title: 'Мужская рубашка(normal)',
    price: '11,00',
    href: '/shop?id=7',
    src: 'public/images/8_Мужская_рубашка_normal__src.jpg',
    hoverSrc: 'public/images/8_Мужская_рубашка_normal__src.jpg',
    season: 'Зима',
    category: 'Курки',
    images: [
      'public/images/shop/2_Куртка__normal/01.jpeg',
      'public/images/shop/2_Куртка__normal/02.jpeg',
      'public/images/shop/2_Куртка__normal/03.jpeg',
      'public/images/shop/2_Куртка__normal/04.jpg',
      'public/images/shop/2_Куртка__normal/05.jpg',
      'public/images/shop/2_Куртка__normal/06.jpg',
      'public/images/shop/2_Куртка__normal/07.jpg',
      'public/images/shop/2_Куртка__normal/08.jpg',
      'public/images/shop/2_Куртка__normal/09.jpg',
      'public/images/shop/2_Куртка__normal/10.jpg',
      'public/images/shop/2_Куртка__normal/11.jpg',
      'public/images/shop/2_Куртка__normal/12.jpg',
      'public/images/shop/2_Куртка__normal/13.jpg',
    ],
  },
  {
    title: 'Мужской бомбер(oversize)',
    price: '29,00',
    href: '/shop?id=8',
    src: 'public/images/9_Мужской_бомбер_oversize__src.jpg',
    hoverSrc: 'public/images/9_Мужской_бомбер_oversize__hover.jpg',
    season: 'Зима',
    category: 'Курки',
    images: [
      'public/images/shop/2_Куртка__normal/01.jpeg',
      'public/images/shop/2_Куртка__normal/02.jpeg',
      'public/images/shop/2_Куртка__normal/03.jpeg',
      'public/images/shop/2_Куртка__normal/04.jpg',
      'public/images/shop/2_Куртка__normal/05.jpg',
      'public/images/shop/2_Куртка__normal/06.jpg',
      'public/images/shop/2_Куртка__normal/07.jpg',
      'public/images/shop/2_Куртка__normal/08.jpg',
      'public/images/shop/2_Куртка__normal/09.jpg',
      'public/images/shop/2_Куртка__normal/10.jpg',
      'public/images/shop/2_Куртка__normal/11.jpg',
      'public/images/shop/2_Куртка__normal/12.jpg',
      'public/images/shop/2_Куртка__normal/13.jpg',
    ],
  },
  {
    title: 'Мужской кардиган (normal)',
    price: '15,50',
    href: '/shop?id=9',
    src: 'public/images/10_Мужской_кардиган__normal__src.jpg',
    hoverSrc: 'public/images/10_Мужской_кардиган__normal__hover.jpg',
    season: 'Зима',
    category: 'Курки',
    images: [
      'public/images/shop/2_Куртка__normal/01.jpeg',
      'public/images/shop/2_Куртка__normal/02.jpeg',
      'public/images/shop/2_Куртка__normal/03.jpeg',
      'public/images/shop/2_Куртка__normal/04.jpg',
      'public/images/shop/2_Куртка__normal/05.jpg',
      'public/images/shop/2_Куртка__normal/06.jpg',
      'public/images/shop/2_Куртка__normal/07.jpg',
      'public/images/shop/2_Куртка__normal/08.jpg',
      'public/images/shop/2_Куртка__normal/09.jpg',
      'public/images/shop/2_Куртка__normal/10.jpg',
      'public/images/shop/2_Куртка__normal/11.jpg',
      'public/images/shop/2_Куртка__normal/12.jpg',
      'public/images/shop/2_Куртка__normal/13.jpg',
    ],
  },
]
