export const cards = [
  {
    title: 'Водолазка(normal)',
    price: '13,5',
    href: '#',
    src: 'public/images/1_Водолазка_normal__hover.jpg',
    hoverSrc: 'public/images/1_Водолазка_normal__hover.jpg',
  },
  {
    title: 'Куртка (normal)',
    price: '49,00',
    href: '#',
    src: 'public/images/2_Куртка__normal__src.jpeg',
    hoverSrc: 'public/images/2_Куртка__normal__src.jpeg',
  },
  {
    title: 'Куртка (normal)',
    price: '49,50',
    href: '#',
    src: 'public/images/3_Куртка__normal__src.jpg',
    hoverSrc: 'public/images/3_Куртка__normal__hover.jpg',
  },
  {
    title: 'Куртка (oversize)',
    price: '32,00',
    href: '#',
    src: 'public/images/4_Куртка__oversize__src.jpg',
    hoverSrc: 'public/images/4_Куртка__oversize__hover.jpg',
  },
  {
    title: 'Мужская двойка(normal)',
    price: '29,00',
    href: '#',
    src: 'public/images/5_Мужская_двойка_normal__hover.jpg',
    hoverSrc: 'public/images/5_Мужская_двойка_normal__hover.jpg',
  },
  {
    title: 'Мужская кофта(normal)',
    price: '10,50',
    href: '#',
    src: 'public/images/6_Мужская_кофта_normal__src.jpg',
    hoverSrc: 'public/images/6_Мужская_кофта_normal__hover.jpg',
  },
  {
    title: 'Мужская кофта(normal)',
    price: '12,00',
    href: '#',
    src: 'public/images/7_Мужская_кофта_normal__src.jpg',
    hoverSrc: 'public/images/7_Мужская_кофта_normal__hover.jpg',
  },
  {
    title: 'Мужская рубашка(normal)',
    price: '11,00',
    href: '#',
    src: 'public/images/8_Мужская_рубашка_normal__src.jpg',
    hoverSrc: 'public/images/8_Мужская_рубашка_normal__src.jpg',
  },
  {
    title: 'Мужской бомбер(oversize)',
    price: '29,00',
    href: '#',
    src: 'public/images/9_Мужской_бомбер_oversize__src.jpg',
    hoverSrc: 'public/images/9_Мужской_бомбер_oversize__hover.jpg',
  },
  {
    title: 'Мужской кардиган (normal)',
    price: '15,50',
    href: '#',
    src: 'public/images/10_Мужской_кардиган__normal__src.jpg',
    hoverSrc: 'public/images/10_Мужской_кардиган__normal__hover.jpg',
  },
]
