export const cards = [
  {
    title: 'Водолазка(normal)',
    price: '13,5',
    href: '/shop?id=0',
    src: 'public/images/1_Водолазка_normal__src.jpg',
    hoverSrc: 'public/images/1_Водолазка_normal__hover.jpg',
    season: 'Осень',
    category: 'Водолазка',
    colors: [
      {
        color: 'Бежевый',
        src: 'public/images/shop/1_Водолазка_normal/05.jpg',
        background: '#f5f5dc',
      }, // бежевый
      {
        color: 'Бирюзовый',
        src: 'public/images/shop/1_Водолазка_normal/13.jpg',
        background: '#40e0d0',
      }, // бирюзовый
      {
        color: 'Коричневый',
        src: 'public/images/shop/1_Водолазка_normal/09.jpg',
        background: '#8b4513',
      }, // коричневый
      {
        color: 'Бордовый',
        src: 'public/images/shop/1_Водолазка_normal/01.jpg',
        background: '#800000',
      }, // бордовый
    ],
    sku: '#К-709',
    material: 'Трикотаж',
    sizes: ['3XL', 'L', 'M', 'S', 'S-3XL', 'XL'],
    images: [
      'public/images/shop/1_Водолазка_normal/01.jpg',
      'public/images/shop/1_Водолазка_normal/02.jpg',
      'public/images/shop/1_Водолазка_normal/03.jpg',
      'public/images/shop/1_Водолазка_normal/04.jpg',
      'public/images/shop/1_Водолазка_normal/05.jpg',
      'public/images/shop/1_Водолазка_normal/06.jpg',
      'public/images/shop/1_Водолазка_normal/07.jpg',
      'public/images/shop/1_Водолазка_normal/08.jpg',
      'public/images/shop/1_Водолазка_normal/09.jpg',
      'public/images/shop/1_Водолазка_normal/10.jpg',
      'public/images/shop/1_Водолазка_normal/11.jpg',
      'public/images/shop/1_Водолазка_normal/12.jpg',
      'public/images/shop/1_Водолазка_normal/14.jpg',
      'public/images/shop/1_Водолазка_normal/15.jpg',
      'public/images/shop/1_Водолазка_normal/16.jpg',
    ],
  },
  {
    title: 'Куртка (normal)',
    price: '49,00',
    href: '/shop?id=1',
    src: 'public/images/2_Куртка__normal__src.jpeg',
    hoverSrc: 'public/images/2_Куртка__normal__hover.jpeg',
    season: 'Зима',
    sku: '#88-137',
    category: 'Курки',
    images: [
      'public/images/shop/2_Куртка__normal/01.jpeg',
      'public/images/shop/2_Куртка__normal/02.jpeg',
      'public/images/shop/2_Куртка__normal/03.jpeg',
      'public/images/shop/2_Куртка__normal/04.jpg',
      'public/images/shop/2_Куртка__normal/05.jpg',
      'public/images/shop/2_Куртка__normal/06.jpg',
      'public/images/shop/2_Куртка__normal/07.jpg',
      'public/images/shop/2_Куртка__normal/08.jpg',
      'public/images/shop/2_Куртка__normal/09.jpg',
      'public/images/shop/2_Куртка__normal/10.jpg',
      'public/images/shop/2_Куртка__normal/11.jpg',
      'public/images/shop/2_Куртка__normal/12.jpg',
      'public/images/shop/2_Куртка__normal/13.jpg',
    ],
  },
  {
    title: 'Куртка (normal)',
    price: '49,50',
    href: '/shop?id=2',
    src: 'public/images/3_Куртка__normal__src.jpg',
    hoverSrc: 'public/images/3_Куртка__normal__hover.jpg',
    season: 'Зима',
    category: 'Курки',
    sku: 'N/A',
    material: 'Матовая плащевка',
    colors: ['Коричневый', 'Серый', 'Темно-серый'],
    images: [
      'public/images/shop/3_Куртка__normal/01.jpg',
      'public/images/shop/3_Куртка__normal/02.jpg',
      'public/images/shop/3_Куртка__normal/03.jpg',
      'public/images/shop/3_Куртка__normal/04.jpg',
      'public/images/shop/3_Куртка__normal/05.jpg',
      'public/images/shop/3_Куртка__normal/06.jpg',
      'public/images/shop/3_Куртка__normal/07.jpg',
      'public/images/shop/3_Куртка__normal/08.jpg',
      'public/images/shop/3_Куртка__normal/09.jpg',
    ],
  },
  {
    title: 'Куртка (oversize)',
    price: '32,00',
    href: '/shop?id=3',
    src: 'public/images/4_Куртка__oversize__src.jpg',
    hoverSrc: 'public/images/4_Куртка__oversize__hover.jpg',
    season: 'Зима',
    sku: '#М-795',
    category: 'Куртки',
    material: 'Плащевка',
    colors: [
      'Бежевый',
      'Ментол',
      'Парламент',
      'Серый',
      'Темно-серый',
      'Хакки',
      'Черный',
    ],
    sizes: ['L', 'M', 'XL', 'XXL'],
    images: [
      'public/images/shop/4_Куртка__oversize/01.jpg',
      'public/images/shop/4_Куртка__oversize/02.jpg',
      'public/images/shop/4_Куртка__oversize/03.jpg',
      'public/images/shop/4_Куртка__oversize/04.jpg',
      'public/images/shop/4_Куртка__oversize/05.jpg',
      'public/images/shop/4_Куртка__oversize/06.jpg',
      'public/images/shop/4_Куртка__oversize/07.jpg',
      'public/images/shop/4_Куртка__oversize/08.jpg',
      'public/images/shop/4_Куртка__oversize/09.jpg',
      'public/images/shop/4_Куртка__oversize/10.jpg',
      'public/images/shop/4_Куртка__oversize/11.jpg',
      'public/images/shop/4_Куртка__oversize/12.jpg',
      'public/images/shop/4_Куртка__oversize/13.jpg',
      'public/images/shop/4_Куртка__oversize/14.jpg',
    ],
  },
  {
    title: 'Мужская двойка(normal)',
    price: '29,00',
    href: '/shop?id=4',
    src: 'public/images/5_Мужская_двойка_normal__hover.jpg',
    hoverSrc: 'public/images/5_Мужская_двойка_normal__hover.jpg',
    season: 'Осень',
    sku: '#М-795',
    category: 'Спорт костюм',
    material: 'Хлопок с флисом',
    colors: ['Петроль', 'Фиолетовый', 'Черный'],
    sizes: ['L', 'M', 'S', 'XL', 'XXL'],
    images: [
      'public/images/shop/5_Мужская__двойка_normal/01.jpg',
      'public/images/shop/5_Мужская__двойка_normal/02.jpg',
      'public/images/shop/5_Мужская__двойка_normal/03.jpg',
      'public/images/shop/5_Мужская__двойка_normal/04.jpg',
      'public/images/shop/5_Мужская__двойка_normal/05.jpg',
      'public/images/shop/5_Мужская__двойка_normal/06.jpg',
      'public/images/shop/5_Мужская__двойка_normal/07.jpg',
      'public/images/shop/5_Мужская__двойка_normal/08.jpg',
      'public/images/shop/5_Мужская__двойка_normal/09.jpg',
      'public/images/shop/5_Мужская__двойка_normal/10.jpg',
      'public/images/shop/5_Мужская__двойка_normal/11.jpg',
      'public/images/shop/5_Мужская__двойка_normal/12.jpg',
      'public/images/shop/5_Мужская__двойка_normal/13.jpg',
      'public/images/shop/5_Мужская__двойка_normal/14.jpg',
      'public/images/shop/5_Мужская__двойка_normal/15.jpg',
      'public/images/shop/5_Мужская__двойка_normal/16.jpg',
      'public/images/shop/5_Мужская__двойка_normal/17.jpg',
      'public/images/shop/5_Мужская__двойка_normal/18.jpg',
      'public/images/shop/5_Мужская__двойка_normal/19.jpg',
      'public/images/shop/5_Мужская__двойка_normal/20.jpg',
      'public/images/shop/5_Мужская__двойка_normal/21.jpg',
    ],
  },
  {
    title: 'Мужская кофта(normal)',
    price: '10,50',
    href: '/shop?id=5',
    src: 'public/images/6_Мужская_кофта_normal__src.jpg',
    hoverSrc: 'public/images/6_Мужская_кофта_normal__hover.jpg',
    season: 'Осень',
    sku: '#М-113',
    category: 'Кофты',
    material: 'Хлопок с флисом',
    colors: ['Петроль', 'Фиолетовый', 'Черный'],
    sizes: ['L', 'M', 'S', 'XL', 'XXL'],

    images: [
      'public/images/shop/6_Мужская_кофта_normal/01.jpg',
      'public/images/shop/6_Мужская_кофта_normal/02.jpg',
      'public/images/shop/6_Мужская_кофта_normal/03.jpg',
      'public/images/shop/6_Мужская_кофта_normal/04.jpg',
      'public/images/shop/6_Мужская_кофта_normal/05.jpg',
      'public/images/shop/6_Мужская_кофта_normal/06.jpg',
      'public/images/shop/6_Мужская_кофта_normal/07.jpg',
      'public/images/shop/6_Мужская_кофта_normal/08.jpg',
      'public/images/shop/6_Мужская_кофта_normal/09.jpg',
      'public/images/shop/6_Мужская_кофта_normal/10.jpg',
      'public/images/shop/6_Мужская_кофта_normal/11.jpg',
      'public/images/shop/6_Мужская_кофта_normal/12.jpg',
    ],
  },
  {
    title: 'Мужская кофта(normal)',
    price: '12,00',
    href: '/shop?id=6',
    src: 'public/images/7_Мужская_кофта_normal__src.jpg',
    hoverSrc: 'public/images/7_Мужская_кофта_normal__hover.jpg',
    season: 'Осень',
    sku: '#21-0000154',
    category: 'Кофты',
    material: 'Трикотаж',
    colors: [
      'Антрацитовый',
      'Красный',
      'Серый',
      'Синий меланж',
      'Темно-бежевый',
      'Темно-зеленый',
      'Темно-серый',
      'Темно-синий',
      'Фиолетовый меланж',
      'Черный',
    ],
    sizes: ['3XL', 'L', 'M', 'XL', 'XXL'],

    images: [
      'public/images/shop/7_Мужская_кофта_normal/01.jpg',
      'public/images/shop/7_Мужская_кофта_normal/02.jpg',
      'public/images/shop/7_Мужская_кофта_normal/03.jpg',
      'public/images/shop/7_Мужская_кофта_normal/04.jpg',
      'public/images/shop/7_Мужская_кофта_normal/05.jpg',
      'public/images/shop/7_Мужская_кофта_normal/06.jpg',
      'public/images/shop/7_Мужская_кофта_normal/07.jpg',
      'public/images/shop/7_Мужская_кофта_normal/08.jpg',
      'public/images/shop/7_Мужская_кофта_normal/09.jpg',
      'public/images/shop/7_Мужская_кофта_normal/10.jpg',
      'public/images/shop/7_Мужская_кофта_normal/11.jpg',
      'public/images/shop/7_Мужская_кофта_normal/12.jpg',
      'public/images/shop/7_Мужская_кофта_normal/13.jpg',
    ],
  },
  {
    title: 'Мужская рубашка(normal)',
    price: '11,00',
    href: '/shop?id=7',
    src: 'public/images/8_Мужская_рубашка_normal__src.jpg',
    hoverSrc: 'public/images/8_Мужская_рубашка_normal__src.jpg',
    season: '',
    sku: '#4597',
    category: 'Рубашки',
    material: 'Байка',
    colors: ['Белый', 'Темно-серый', 'Темно-синий'],
    sizes: ['3XL', 'L', 'M', 'XL', 'XXL'],

    images: [
      'public/images/shop/8_Мужская_рубашка_normal/01.jpg',
      'public/images/shop/8_Мужская_рубашка_normal/02.jpg',
      'public/images/shop/8_Мужская_рубашка_normal/03.jpg',
      'public/images/shop/8_Мужская_рубашка_normal/04.jpg',
      'public/images/shop/8_Мужская_рубашка_normal/05.jpg',
      'public/images/shop/8_Мужская_рубашка_normal/06.jpg',
      'public/images/shop/8_Мужская_рубашка_normal/07.jpg',
      'public/images/shop/8_Мужская_рубашка_normal/08.jpg',
      'public/images/shop/8_Мужская_рубашка_normal/09.jpg',
      'public/images/shop/8_Мужская_рубашка_normal/10.jpg',
      'public/images/shop/8_Мужская_рубашка_normal/11.jpg',
      'public/images/shop/8_Мужская_рубашка_normal/12.jpg',
      'public/images/shop/8_Мужская_рубашка_normal/13.jpg',
    ],
  },
  {
    title: 'Мужской бомбер(oversize)',
    price: '29,00',
    href: '/shop?id=8',
    src: 'public/images/9_Мужской_бомбер_oversize__src.jpg',
    hoverSrc: 'public/images/9_Мужской_бомбер_oversize__hover.jpg',
    season: 'Зима',
    sku: '#4707',
    category: 'Курки',
    material: 'Альпака',
    colors: ['Бежевый', 'Темно-серый', 'Черный'],
    sizes: ['L', 'M', 'S', 'XL'],

    images: [
      'public/images/shop/9_Мужской_бомбер_oversize/01.jpg',
      'public/images/shop/9_Мужской_бомбер_oversize/02.jpg',
      'public/images/shop/9_Мужской_бомбер_oversize/03.jpg',
      'public/images/shop/9_Мужской_бомбер_oversize/04.jpg',
      'public/images/shop/9_Мужской_бомбер_oversize/05.jpg',
      'public/images/shop/9_Мужской_бомбер_oversize/06.jpg',
      'public/images/shop/9_Мужской_бомбер_oversize/07.jpg',
      'public/images/shop/9_Мужской_бомбер_oversize/08.jpg',
      'public/images/shop/9_Мужской_бомбер_oversize/09.jpg',
      'public/images/shop/9_Мужской_бомбер_oversize/10.jpg',
      'public/images/shop/9_Мужской_бомбер_oversize/11.jpg',
      'public/images/shop/9_Мужской_бомбер_oversize/12.jpg',
    ],
  },
  {
    title: 'Мужской кардиган (normal)',
    price: '15,50',
    href: '/shop?id=9',
    src: 'public/images/10_Мужской_кардиган__normal__src.jpg',
    hoverSrc: 'public/images/10_Мужской_кардиган__normal__hover.jpg',
    season: 'Зима',
    sku: '#К-702',
    category: 'Кардиган',
    material: 'Трикотаж',
    colors: [
      'Айвори',
      'Индиго Меланж',
      'Коралловый',
      'Светло-серый',
      'Темно-бежевый',
    ],
    sizes: ['L', 'M', 'XL', 'XXL'],

    images: [
      'public/images/shop/10_Мужской_кардиган__normal/01.jpg',
      'public/images/shop/10_Мужской_кардиган__normal/02.jpg',
      'public/images/shop/10_Мужской_кардиган__normal/03.jpg',
      'public/images/shop/10_Мужской_кардиган__normal/04.jpg',
      'public/images/shop/10_Мужской_кардиган__normal/05.jpg',
      'public/images/shop/10_Мужской_кардиган__normal/06.jpg',
      'public/images/shop/10_Мужской_кардиган__normal/07.jpg',
      'public/images/shop/10_Мужской_кардиган__normal/08.jpg',
      'public/images/shop/10_Мужской_кардиган__normal/09.jpg',
      'public/images/shop/10_Мужской_кардиган__normal/10.jpg',
      'public/images/shop/10_Мужской_кардиган__normal/11.jpg',
      'public/images/shop/10_Мужской_кардиган__normal/12.jpg',
    ],
  },
]
